script: true
deploy:
  provider: openshift
  user: $EMAIL_ADDRESS
  password:
    secure: Q/Ruod5Ws8PfEuxCra0XK+aPy3YIyMDZL05Kifdt76HXLTZd6bGNiGZZkX66KGrZ0Z89d0uQ7Pt7dxoj6eUOM7EKINTEZnC8gl4Xz1C9KO/KSYB5U46C9pyGhWdJj5LAzTotMQJ1I7d6Ze3ClWTgTvXj+kS+fO4H4eF91h8PWomk7U3MdYqqYV3DmWUSHUGBo6xhbc/Og+3M4tvyZwwEwCfG6VFcUnrMueU2OA0blYsz/6hf/buIG8tZRyzPmpEa4H+Pu9QfBVt3ooqx/bMhlHsa7sr7u5AQI2d4q4Iuk06nqUfPQ74sueX1YppMMlYEzElbBVTnJZkvRj6TvdVrUy9c5lUqcLu7s+3WAlF86DnklOVQDLmAiFSHJ0SOfHeI2ZOkFv3u4CeQjZxQLm3x6q7SPyRHJ9FUlHe1Hp2iIzpXs2X0vr3N1EXlTPX6ambDJTpEDcCQjG8rGJcTUbc8SLg0Oq+jDVwUW9/YVlNAdegjneqypMxSj2iE8TriYNKNMbeKgXWabFDowGCPzocRDBoqlAJTRfyps9CR38QOXDqwOYrMkqDD6y39QKUO4PAiLfAdWxF3zPMZ2G4jepOJA2rz2IfQm3wvjEpOldh59Y1wAzod9RVN0vMU9yub4dnYwxtQRO9RJh8LWy00+1IS/oBEJVSA38qFdsZ119Y2weU=
  app: $APP_NAME
  domain: $DOMAIN_NAME
  on: master